[package]
name = "rust-trpc"
version = "0.1.0"
edition = "2021"


[[bin]] # Bin to run the gRPC server
name = "server"
path = "src/server.rs"

[dependencies]
prost = "0.11.6"
tokio ={version = "1.25.0" , features = ["full"]}
tonic = "0.8.3"


[build-dependencies]
tonic-build = "0.8.3"